### ISSUE TITLE
logsql.sqlite not found

### ISSUE THREAD

**Issue by darrenangwx** [DinoTools/dionaea-docker#2]
Hi, may i know if logsql.sqlite is created?
Wondering if i can use Dionaeafr together with this dionaea docker

**Comment by phibos** [comment]
This container should be used as a base container and most of the ihandlers are not activated by default. You can create you own customized container and add all required ihandler configs to /opt/dionaea/etc/dionaea/ihandlers or you can use a volume to provide all required config files.

Feel free to have a look at the README.md for additional information on how to create your own Docker container and add your custom config files.

**Comment by darrenangwx** [comment]
Thanks for your reply. Manage to get dionaea.sqlite working as intended.
Another question, for capturing of binaries to /opt/dionaea/var/dionaea/binaries, is it activated by default or are some extra configuration needed for it to start capturing binaries?

**Comment by phibos** [comment]
The ```store``` ihandler is activated by default and dionaea should dump all binaries into the ```download.dir```.

**Comment by darrenangwx** [comment]
Thank you for answering. Everything is working as intended now. 👍
